
name: Data Analysis

on:
  push:
    branches:
      - main

jobs:
  analyze_data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl

    - name: Run Data Analysis
      run: python main.py 

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: regression-plots
        path: |
          plot_test_size_0.2.png
          plot_test_size_0.3.png
          plot_test_size_0.4.png
